name: promice-iv
channels:
  - conda-forge
dependencies:
  - bottleneck
  - dask
  - IPython
  - matplotlib
  - netCDF4
  - numpy
  - pandas
  - pip
  - python>=3.11
  - requests
  - scipy
  - xarray
  - pip:
      - beautifulsoup4
      - siphon
